name: Self-Hosted Runner Test 🚀

on:
  push:
    branches: [ main ]

jobs:
  runner-test:
    name: Test Our AWS Runner 🏗️
    runs-on: self-hosted

    steps:
      - name: Checkout Code 📂
        uses: actions/checkout@v4

      - name: Print Machine Information 💻
        run: |
          echo "Hostname: $(hostname)"
          echo "User: $(whoami)"
          echo "Uptime:"
          uptime

      - name: Print Custom Message 💬
        run: echo "Hello from AWS self-hosted runner!"